version: '3.9'

services:
  db:
    image: mysql:8.0.28-oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Test123!
    ports:
      - 3306:3306